/* Generated By:JavaCC: Do not edit this line. DomconOzInputCodecConstants.java */
package de.saar.chorus.domgraph.codec.domcon;

public interface DomconOzInputCodecConstants {

  int EOF = 0;
  int PERCENT_COMMENT = 5;
  int LABEL = 6;
  int DOM = 7;
  int OZATOM = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<PERCENT_COMMENT>",
    "\"label\"",
    "\"dom\"",
    "<OZATOM>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
