/* Generated By:JavaCC: Do not edit this line. GlueInputCodecConstants.java */
package de.saar.chorus.domgraph.codec.glue;

public interface GlueInputCodecConstants {

  int EOF = 0;
  int PERCENT_COMMENT = 5;
  int IMP = 6;
  int VAR = 7;
  int ATOM = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<PERCENT_COMMENT>",
    "\"-o\"",
    "<VAR>",
    "<ATOM>",
    "\"[\"",
    "\",\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
