<type_info>
  <hierarchy>
    <entry>
      <ctype>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="psych_state"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="love"/>
        <type val="psych_state"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="event"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="entity"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="entity"/>
        <type val="person"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="activity"/>
        <type val="event"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
    <entry>
      <ctype>
        <type val="activity"/>
        <type val="event"/>
        <type val="sleep"/>
      </ctype>
      <constraints>
      </constraints>
    </entry>
  </hierarchy>
  <type_constraints>
    <type_constraint type="implies">
      <ctype1>
        <type val="person"/>
      </ctype1>
      <ctype2>
        <type val="entity"/>
      </ctype2>
    </type_constraint>
    <type_constraint type="implies">
      <ctype1>
        <type val="sleep"/>
      </ctype1>
      <ctype2>
        <type val="activity"/>
      </ctype2>
    </type_constraint>
    <type_constraint type="implies">
      <ctype1>
        <type val="love"/>
      </ctype1>
      <ctype2>
        <type val="psych_state"/>
      </ctype2>
    </type_constraint>
    <type_constraint type="implies">
      <ctype1>
        <type val="entity"/>
        <type val="psych_state"/>
      </ctype1>
      <ctype2>
        <type val="false"/>
      </ctype2>
    </type_constraint>
    <type_constraint type="implies">
      <ctype1>
        <type val="entity"/>
        <type val="event"/>
      </ctype1>
      <ctype2>
        <type val="false"/>
      </ctype2>
    </type_constraint>
    <type_constraint type="implies">
      <ctype1>
        <type val="psych_state"/>
        <type val="event"/>
      </ctype1>
      <ctype2>
        <type val="false"/>
      </ctype2>
    </type_constraint>
    <type_constraint type="implies">
      <ctype1>
        <type val="activity"/>
      </ctype1>
      <ctype2>
        <type val="event"/>
      </ctype2>
    </type_constraint>
  </type_constraints>
</type_info>
