/* Generated By:JavaCC: Do not edit this line. MrsPrologInputCodecConstants.java */
package de.saar.chorus.domgraph.codec.mrs;

public interface MrsPrologInputCodecConstants {

  int EOF = 0;
  int COMMENT = 5;
  int PSOA = 6;
  int REL = 7;
  int ATTRVAL = 8;
  int HCONS = 9;
  int QEQ = 10;
  int HANDLE = 11;
  int VARIABLE = 12;
  int OTHER = 13;
  int SYMBOL = 14;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"psoa\"",
    "\"rel\"",
    "\"attrval\"",
    "\"hcons\"",
    "<QEQ>",
    "<HANDLE>",
    "<VARIABLE>",
    "<OTHER>",
    "<SYMBOL>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
  };

}
