/* Generated By:JavaCC: Do not edit this line. HolesemComsemInputCodecConstants.java */
package de.saar.chorus.domgraph.codec.holesem;

public interface HolesemComsemInputCodecConstants {

  int EOF = 0;
  int PERCENT_COMMENT = 5;
  int HOLE = 6;
  int LABEL = 7;
  int SOME = 8;
  int AND = 9;
  int OR = 10;
  int IMP = 11;
  int NOT = 12;
  int ALL = 13;
  int LEQ = 14;
  int QUE = 15;
  int EQ = 16;
  int PRED1 = 17;
  int PRED2 = 18;
  int PLATOM = 19;
  int PLVAR = 20;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<PERCENT_COMMENT>",
    "\"hole\"",
    "\"label\"",
    "\"some\"",
    "\"and\"",
    "\"or\"",
    "\"imp\"",
    "\"not\"",
    "\"all\"",
    "\"leq\"",
    "\"que\"",
    "\"eq\"",
    "\"pred1\"",
    "\"pred2\"",
    "<PLATOM>",
    "<PLVAR>",
    "\"(\"",
    "\",\"",
    "\")\"",
  };

}
